# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_Chat(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(923, 698)
        self.layoutWidget = QWidget(Form)
        self.textBrowser = QTextBrowser()
        self.textEdit = QTextEdit()
        self.label_image = QLabel()
        self.label_nickname = QLabel()
        self.label_signature = QLabel()
        self.label_signature.setWordWrap(True)
        self.label_signature.setMaximumWidth(400)
        self.label_region = QLabel()
        self.label_birthday = QLabel()
        self.label_margin = QLabel()
        self.pushButton = QPushButton()
        self.pushButton.setText('发送')
        self.pushButton.setToolTip('按Ctrl+Enter键快捷发送')

        self.main_layout = QHBoxLayout()
        self.h_layout = QHBoxLayout()
        self.vl_layout = QVBoxLayout()
        self.vr_layout = QVBoxLayout()

        self.vr_layout.addWidget(self.label_image)
        self.vr_layout.addWidget(self.label_nickname)
        self.vr_layout.addWidget(self.label_birthday)
        self.vr_layout.addWidget(self.label_region)
        self.vr_layout.addWidget(self.label_signature)

        self.h_layout.addWidget(self.label_margin)
        self.h_layout.addWidget(self.label_margin)
        self.h_layout.addWidget(self.pushButton)

        self.vl_layout.addWidget(self.textBrowser)
        self.vl_layout.addWidget(self.textEdit)
        self.vl_layout.addLayout(self.h_layout)
        self.vl_layout.setStretchFactor(self.textBrowser, 3)
        self.vl_layout.setStretchFactor(self.textEdit, 1)

        self.main_layout.addLayout(self.vl_layout)
        self.main_layout.addLayout(self.vr_layout)
        self.layoutWidget.setLayout(self.main_layout)
